spring:
  datasource:
    username: root
    password: chenxiang
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    DriverClassName: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
